run: Chess.class Board.class Square.class Pawn.class Rook.class Knight.class Bishop.class King.class Queen.class GamePiece.class
	java Chess
clean:
	rm *.class
test: TestChess.class Chess.class Board.class Square.class Pawn.class Rook.class Knight.class Bishop.class King.class Queen.class GamePiece.class
	java TestChess

# .class dependencies
Chess.class: Chess.java
	javac Chess.java
Board.class: Board.java
	javac Board.java
Square.class: Square.java
	javac Square.java
Pawn.class: Pawn.java
	javac Pawn.java
Rook.class: Rook.java
	javac Rook.java
Knight.class: Knight.java
	javac Knight.java
Bishop.class: Bishop.java
	javac Bishop.java
King.class: King.java
	javac King.java
Queen.class: Queen.java
	javac Queen.java
GamePiece.class: GamePiece.java
	javac GamePiece.java
TestChess.class: TestChess.java
	javac TestChess.java